/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M4
 * Generated at: 2016-11-14 10:58:28 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class contact_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/_include/menu.jsp", Long.valueOf(1479121096829L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<title>Contact us</title>\n");
      out.write("<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("    <div id=\"container\">\n");
      out.write("\t<center>\n");
      out.write("\t\t<p style=\"color:#088A85\" align=\"center\" ><font face=\"Algerian\" size=\"500\">GAMEBOARD WORLD</font><a href=\"https://www.facebook.com/%E5%A4%A9%E5%A4%A9%E5%AD%B8%E6%A1%8C%E9%81%8A-1118376901610135/\"  target=\"_blank\" ><img src=\"fb.png\" style=\"width:50px;height:40px;\" align=\"right\"></a>\n");
      out.write("\t\t<a href=\"https://www.facebook.com/%E5%A4%A9%E5%A4%A9%E5%AD%B8%E6%A1%8C%E9%81%8A-1118376901610135/\"  target=\"_blank\" ><img src=\"in.png\" style=\"width:50px;height:40px;\" align=\"right\"></a></p>\n");
      out.write("\t\t<hr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<style >\n");
      out.write("h1 {\n");
      out.write("    font-size: 700%;\n");
      out.write("\t\n");
      out.write("}\n");
      out.write("ul {\n");
      out.write("    list-style-type: none;\n");
      out.write("    margin: 0;\n");
      out.write("    padding: 0;\n");
      out.write("    overflow: hidden;\n");
      out.write("    background-color: #0B615E;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li {\n");
      out.write("\n");
      out.write("    float: left;\n");
      out.write("    border-right:1px solid #bbb;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li:last-child {\n");
      out.write("    border-right: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li a {\n");
      out.write("    display: block;\n");
      out.write("    color: white;\n");
      out.write("    text-align: center;\n");
      out.write("    padding: 14px 16px;\n");
      out.write("    text-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li a:hover:not(.active) {\n");
      out.write("    background-color: #111;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".active {\n");
      out.write("    background-color: #4CAF50;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<center>\n");
      out.write("<table style=\"border: 0px solid #0B614B;\" style=\"width:100%\">\n");
      out.write("\t<tr>\n");
      out.write("\t<th>\n");
      out.write("\t<image src=LOGODC2.png width=\"100px\" height=\"90\">\n");
      out.write("\t</th>\n");
      out.write("\t\t<th>\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t\t  \n");
      out.write("\t\t\t\t  <li><a class=\"active\" href=\"index.jsp\" target=\"_self\">Home</a></li>\n");
      out.write("\t\t\t\t  <li><a href=\"index4.jsp\" target=\"_self\">Shop</a></li>\n");
      out.write("\t\t\t\t  <li><a href=\"book.jsp\" target=\"_self\">Order</a></li>\n");
      out.write("\t\t\t\t  \n");
      out.write("\t\t\t\t  <li><a href=\"contact.jsp\" target=\"_self\">Contact us</a></li>\n");
      out.write("\t\t\t\t  <li><a href=\"video.jsp\" target=\"_self\">Video</a></li>\n");
      out.write("\t\t\t\t  <li class=\"m-5\"><a href=\"rent.jsp\" target=\"_self\">Status</a></li>\n");
      out.write("\t\t\t\t  <li style=\"float:right\"><a href=\"register.jsp\" target=\"_self\">Sign up</a></li>\n");
      out.write("\t\t\t\t  <li class=\"m-7\"><a href=\"login.jsp\" target=\"_self\">\n");
      out.write("\t\t\t\t");
	if ( session.getAttribute ("member_name") != null) {
      out.write("\n");
      out.write("\t\t\t\tMODIFY\n");
      out.write("\t\t\t\t");
} else {
      out.write("\n");
      out.write("\t\t\t\tSign in\n");
      out.write("\t\t\t\t");
}
      out.write("\n");
      out.write("\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t");
	if ( session.getAttribute ("member_name") != null) {
      out.write("\n");
      out.write("\t\t\t\t<li class=\"m-8\"><a href=\"logout.jsp\" target=\"_self\">Log out</a></li>\n");
      out.write("\t\t\t\t");
}
      out.write("\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t\t\t\n");
      out.write("        \n");
      out.write("\n");
      out.write("</th>\n");
      out.write("</table>\n");
      out.write("</center>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t</table></center>\n");
      out.write("        <article>\n");
      out.write("        <aside class=\"aside-left-1\">\n");
      out.write("\t\t\t<div class=\"label ll-6\"></div>\n");
      out.write("            <form id=\"contact_form\">\n");
      out.write("            <input type=\"hidden\" id=\"contactidentity\" name=\"identity\" value=\"\">\n");
      out.write("            \t<p class=\"tp\">滿意度：</p>\n");
      out.write("\t\t\t\t<label class=\"radio\"><input type=\"radio\" name=\"RadioGroup1\" value=\"很滿意\">很滿意</label><br>\n");
      out.write("                <label class=\"radio\"><input type=\"radio\" name=\"RadioGroup1\" value=\"還可以\">還可以</label><br>\n");
      out.write("                <label class=\"radio\"><input type=\"radio\" name=\"RadioGroup1\" value=\"不滿意\">不滿意</label><br>\n");
      out.write("                <input type=\"text\" id=\"contactname\" name=\"name\" placeholder=\"Name\" class=\"text2 tp\" maxlength=\"20\"><br>\n");
      out.write("                <input type=\"text\" id=\"contactemail\" name=\"email\" placeholder=\"E-mail\" class=\"text2\" maxlength=\"50\"><br>\n");
      out.write("                <input type=\"text\" id=\"contactphone\" name=\"phone\" placeholder=\"phone\" class=\"text2\" maxlength=\"20\"><br>\n");
      out.write("                <textarea id=\"contactmessage\" name=\"message\" placeholder=\"Message\" class=\"text4\"></textarea>\n");
      out.write("                <div class=\"btns\"><input type=\"reset\" value=\"清除\" class=\"login-button\" id=\"contactclear\" ><input type=\"button\" value=\"送出\" class=\"login-button\" onclick=\"form_submit('contact');\" id=\"contactsubmit\" ></div>\n");
      out.write("            </form>\n");
      out.write("            \n");
      out.write("<script src=\"js/jquery.min.js\"></script>\n");
      out.write("<script src=\"js/jquery.easing.1.3.js\"></script>\n");
      out.write("<script src=\"js/jquery.backgroundPosition.js\"></script>\n");
      out.write("<script src=\"js/cs.js\"></script>\n");
      out.write("<script>\n");
      out.write("(function(){\n");
      out.write("\t\n");
      out.write("\t$('.m-6>a').css({color:'#17ade5'});\n");
      out.write("\t\n");
      out.write("\t$(window).resize(function() {\n");
      out.write("\t\t$('article').css({height:$('.aside-left-1').height()+100});\n");
      out.write("\t}).trigger('resize');\n");
      out.write("\t\t\n");
      out.write("})();\n");
      out.write("function form_submit(element) {\n");
      out.write("\n");
      out.write("    var msg = '';\n");
      out.write("    var identity = '';\n");
      out.write("\tvar RadioGroup1 = document.getElementsByName(\"RadioGroup1\");\n");
      out.write("\tfor (var i=0;i<RadioGroup1.length;i++) {\n");
      out.write("        if (RadioGroup1[i].checked) {\n");
      out.write("        \tidentity = RadioGroup1[i].value;\n");
      out.write("        \t$('#'+element+'identity').val(identity);\n");
      out.write("          break;\n");
      out.write("        }\n");
      out.write("      }\n");
      out.write("    \n");
      out.write("\tif (identity == '')\n");
      out.write("\t        msg += '沒有選擇 \"身分\"\\n';\n");
      out.write("    if ($('#'+element+'name').val().length == 0)\n");
      out.write("        msg += '沒有填寫 \"姓名\"\\n';\n");
      out.write("    else if ($('#'+element+'name').val().length < 2)\n");
      out.write("        msg += '\"姓名\"請填寫詳細\\n';\n");
      out.write("\n");
      out.write("    if ($('#'+element+'phone').val().length == 0)\n");
      out.write("        msg += '沒有填寫 \"電話\"\\n';\n");
      out.write("    else if (/\\d{10,}/.test($('#'+element+'phone').val()) === false)\n");
      out.write("        msg += '格式有錯 \"電話\"\\n';\n");
      out.write("\n");
      out.write("    if ($('#'+element+'email').val().length == 0)\n");
      out.write("        msg += '沒有填寫 \"E-mail\"\\n';\n");
      out.write("    else if (/^[\\w-]+(\\.[\\w-]+)*@[\\w-]+(\\.[\\w-]+)+$/.test($('#'+element+'email').val()) === false)\n");
      out.write("        msg += '格式有誤 \"E-mail\"\\n';\n");
      out.write("    \n");
      out.write("    if ($('#'+element+'message').val().length == 0)\n");
      out.write("        msg += '沒有填寫 \"訊息\"\\n';\n");
      out.write("   \n");
      out.write("    if (msg.length == 0){\n");
      out.write("\t\t$('#'+element+'submit').attr('disabled', true);\n");
      out.write("\t\t$('#'+element+'clear').attr('disabled', true);\n");
      out.write("        $.ajax({\n");
      out.write("            url: \"/controller/MailHandler.jsp\",\n");
      out.write("            data:$(\"#\"+element+\"_form\").serialize(),\n");
      out.write("            type: \"POST\",\n");
      out.write("            dataType: \"json\",\n");
      out.write("            success: function(data,textStatus,jqXHR) {\n");
      out.write("            \tconsole.log(data);\n");
      out.write("            \tconsole.log(textStatus);\n");
      out.write("            \tconsole.log(jqXHR);\n");
      out.write("            \tif(data == 2){\n");
      out.write("\t\t\t\t\tconsole.log('寄信成功');\n");
      out.write("            \t\talert('感謝您的來信!將會有專人與您聯繫，謝謝。');\n");
      out.write("            \t}else{\n");
      out.write("            \t\talert('系統錯誤，請通知網站管理員');\n");
      out.write("            \t}\n");
      out.write("            },\n");
      out.write("            error: function(XMLHttpRequest, textStatus, errorThrown) {\n");
      out.write("            \tconsole.log('寄信失敗');\n");
      out.write("            \tconsole.log(\"XMLHttpRequest.status=\"+XMLHttpRequest.status+\n");
      out.write("\t\t\t    \t\t\"\\nXMLHttpRequest.readyState=\"+XMLHttpRequest.readyState+\"\\ntextStatus=\"+textStatus+\"\\errorThrown=\"+errorThrown);\n");
      out.write("            },\n");
      out.write("            complete: function(XMLHttpRequest) {\n");
      out.write("\t\t\t\t$('#'+element+'submit').attr('disabled', false);\n");
      out.write("                $('#'+element+'clear').attr('disabled', false);\n");
      out.write("            \tconsole.log('寄信結果');\n");
      out.write("            \tconsole.log(XMLHttpRequest);\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("        \t});\n");
      out.write("    }\n");
      out.write("    else{\n");
      out.write("        alert(msg);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    return false;\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
