/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M4
 * Generated at: 2016-11-14 10:58:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;
import teachDB.DbBean;
import org.joda.time.DateTime;
import org.joda.time.Period;
import org.joda.time.PeriodType;

public final class index4_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


	public boolean checkReq(Object obj){
		boolean check = false ;
		if(obj != null && !((String)obj).equals("")){
			check = true;
		}
		return check;
	}
	public Object getReq(Object obj){
		Object getS = "";
		if(obj != null){
			getS = (Date) obj;
		}
		return getS;
	}
	public int[] checkrent(int book_id,int member_id,int book_total){
		int[] result = new int[2];
				DbBean db = new DbBean();
				DateTime nowdate = new DateTime();
				DateTime endtime = nowdate.minusDays(1);
				List whereList = new ArrayList();
				whereList.add(book_id);
				whereList.add(member_id);
				whereList.add(nowdate.toString("yyyy-MM-dd HH:mm:ss"));
				whereList.add(endtime.toString("yyyy-MM-dd HH:mm:ss"));	
				List whereList2 = new ArrayList();
				whereList2.add(book_id);
				whereList2.add(member_id);
				whereList2.add(nowdate.toString("yyyy-MM-dd HH:mm:ss"));		
				List duringReserve = db.SelectRSwhere("select * from borrow_record where book_id = ? and member_id = ? and reserve_date <= ? and reserve_deadline >= ? and borrow_date is null and return_date is null and givefine = 0  ",whereList);
				List overReserve   = db.SelectRSwhere("select * from borrow_record where book_id = ? and member_id = ? and reserve_deadline <= ? and borrow_date is null and return_date is null and givefine = 0  ",whereList2);
				List duringRent    = db.SelectRSwhere("select * from borrow_record where book_id = ? and member_id = ? and borrow_date <= ? and borrow_deadline >= ? and  return_date is null and givefine = 0  ",whereList);
				List overRent	   = db.SelectRSwhere("select * from borrow_record where book_id = ? and member_id = ? and borrow_deadline <= ?  and return_date is null and givefine = 0 ",whereList2);
				List checkList = new ArrayList();
				if(duringReserve != null && duringReserve.size() > 0){
					result[0] = 1;
					checkList.addAll(duringReserve);
				}else if(overReserve != null && overReserve.size() > 0){
					result[0] = 2;
					checkList.addAll(overReserve);
				}else if(duringRent != null && duringRent.size() > 0){
					result[0] = 3;
					checkList.addAll(duringRent);
				}else if(overRent != null && overRent.size() > 0){
					result[0] = 4;
					checkList.addAll(overRent);
				}else if(book_total == 0){
					result[0] = 5;
					result[1] = 0;
				}
				if(checkList != null && checkList.size() > 0){
					for ( int j = 0; j < checkList.size(); j++ ) {
						Map map = (Map) checkList.get(j); 	
			        	int borrow_id  = (Integer)map.get("borrow_id");
						result[1] = borrow_id;	
					}
				}
		return result;
	}
	public String rentState(int rent_id){
		String rent = "";
		switch(rent_id) { 
			case 1: 
				rent = "預約中"; 
				break; 
			case 2: 
				rent = "已超過預約期限"; ; 
				break; 
			case 3: 
				rent = "借閱中"; ; 
				break; 
			case 4: 
				rent = "已超過借閱期限，請盡快還書"; ; 
				break;
			case 5: 
				rent = "書都借光光了，下次請早!"; ; 
				break; 
		} 
		return rent;
	}
	public int getFine(int givefine,int fine,int rent_mark,Object reserve_deadline,Object borrow_deadline){
		int money = 0;
		if(givefine == 1){
			money = fine;
		}else if(rent_mark == 2 || rent_mark == 4){
			DateTime get_deadline = null;
			if(rent_mark == 2 && reserve_deadline != null ){
				get_deadline = new DateTime((Date)reserve_deadline).plusDays(1);
			}else if(rent_mark == 4 && borrow_deadline != null ){
				get_deadline = new DateTime((Date)borrow_deadline).plusDays(1);
			}
			if(get_deadline != null){
				DateTime nowdate = new DateTime();
				Period p = new Period(get_deadline, nowdate, PeriodType.days());
				money = 2 * p.getDays();
			}	
		}
		return money;
	}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/_include/menu.jsp", Long.valueOf(1479121096829L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("org.joda.time.Period");
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("teachDB.DbBean");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("org.joda.time.DateTime");
    _jspx_imports_classes.add("org.joda.time.PeriodType");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');

	request.setCharacterEncoding("UTF-8");
	DbBean  db = new DbBean();
	String firstchoice  = "類別";
	int    secondchoice = 0 ;
	String bookname   = "" ;
	if(checkReq(request.getParameter("firstchoice"))){
		firstchoice = (String)request.getParameter("firstchoice");
	}
	if(checkReq(request.getParameter("secondchoice"))){
		secondchoice = Integer.parseInt((String)request.getParameter("secondchoice"));
	}
	if(checkReq(request.getParameter("bookname"))){
		bookname = (String)request.getParameter("bookname").replaceAll("\\s+", "");
	}

      out.write("\n");
      out.write("<html  ng-app=\"app\" ng-controller= \"mainCrtl\">\n");
      out.write("<head>\n");
      out.write("<style>\n");
      out.write(".button {\n");
      out.write("    background-color: #4CAF50;\n");
      out.write("    border: none;\n");
      out.write("    color: white;\n");
      out.write("    padding: 15px 32px;\n");
      out.write("    text-align: center;\n");
      out.write("    text-decoration: none;\n");
      out.write("    display: inline-block;\n");
      out.write("    font-size: 16px;\n");
      out.write("    margin: 4px 2px;\n");
      out.write("    cursor: pointer;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("<meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\">\n");
      out.write("<meta name=\"apple-mobile-web-app-capable\" content=\"yes\" />\n");
      out.write("<title>天天學桌遊</title>\n");
      out.write("<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("<link rel=\"stylesheet\" href=\"modaal.css\" media=\"screen\">\n");
      out.write("<script src=\"js/angular.js\"></script>\n");
      out.write("<script src=\"js/book.js\"></script>\n");
      out.write("</head>\n");
      out.write("<body > \n");
      out.write("\t\t\n");
      out.write("\t\t<p style=\"color:#088A85\" align=\"center\" ><font face=\"Algerian\" size=\"500\">GAMEBOARD WORLD</font><a href=\"https://www.facebook.com/%E5%A4%A9%E5%A4%A9%E5%AD%B8%E6%A1%8C%E9%81%8A-1118376901610135/\"  target=\"_blank\" ><img src=\"fb.png\" style=\"width:50px;height:40px;\" align=\"right\"></a>\n");
      out.write("\t\t<a href=\"https://www.facebook.com/%E5%A4%A9%E5%A4%A9%E5%AD%B8%E6%A1%8C%E9%81%8A-1118376901610135/\"  target=\"_blank\" ><img src=\"in.png\" style=\"width:50px;height:40px;\" align=\"right\"></a></p>\n");
      out.write("\t\t<hr>\n");
      out.write("\t\t");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<style >\n");
      out.write("h1 {\n");
      out.write("    font-size: 700%;\n");
      out.write("\t\n");
      out.write("}\n");
      out.write("ul {\n");
      out.write("    list-style-type: none;\n");
      out.write("    margin: 0;\n");
      out.write("    padding: 0;\n");
      out.write("    overflow: hidden;\n");
      out.write("    background-color: #0B615E;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li {\n");
      out.write("\n");
      out.write("    float: left;\n");
      out.write("    border-right:1px solid #bbb;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li:last-child {\n");
      out.write("    border-right: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li a {\n");
      out.write("    display: block;\n");
      out.write("    color: white;\n");
      out.write("    text-align: center;\n");
      out.write("    padding: 14px 16px;\n");
      out.write("    text-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li a:hover:not(.active) {\n");
      out.write("    background-color: #111;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".active {\n");
      out.write("    background-color: #4CAF50;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<center>\n");
      out.write("<table style=\"border: 0px solid #0B614B;\" style=\"width:100%\">\n");
      out.write("\t<tr>\n");
      out.write("\t<th>\n");
      out.write("\t<image src=LOGODC2.png width=\"100px\" height=\"90\">\n");
      out.write("\t</th>\n");
      out.write("\t\t<th>\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t\t  \n");
      out.write("\t\t\t\t  <li><a class=\"active\" href=\"index.jsp\" target=\"_self\">Home</a></li>\n");
      out.write("\t\t\t\t  <li><a href=\"index4.jsp\" target=\"_self\">Shop</a></li>\n");
      out.write("\t\t\t\t  <li><a href=\"book.jsp\" target=\"_self\">Order</a></li>\n");
      out.write("\t\t\t\t  \n");
      out.write("\t\t\t\t  <li><a href=\"contact.jsp\" target=\"_self\">Contact us</a></li>\n");
      out.write("\t\t\t\t  <li><a href=\"video.jsp\" target=\"_self\">Video</a></li>\n");
      out.write("\t\t\t\t  <li class=\"m-5\"><a href=\"rent.jsp\" target=\"_self\">Status</a></li>\n");
      out.write("\t\t\t\t  <li style=\"float:right\"><a href=\"register.jsp\" target=\"_self\">Sign up</a></li>\n");
      out.write("\t\t\t\t  <li class=\"m-7\"><a href=\"login.jsp\" target=\"_self\">\n");
      out.write("\t\t\t\t");
	if ( session.getAttribute ("member_name") != null) {
      out.write("\n");
      out.write("\t\t\t\tMODIFY\n");
      out.write("\t\t\t\t");
} else {
      out.write("\n");
      out.write("\t\t\t\tSign in\n");
      out.write("\t\t\t\t");
}
      out.write("\n");
      out.write("\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t");
	if ( session.getAttribute ("member_name") != null) {
      out.write("\n");
      out.write("\t\t\t\t<li class=\"m-8\"><a href=\"logout.jsp\" target=\"_self\">Log out</a></li>\n");
      out.write("\t\t\t\t");
}
      out.write("\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t\t\t\n");
      out.write("        \n");
      out.write("\n");
      out.write("</th>\n");
      out.write("</table>\n");
      out.write("</center>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("\t\t\n");
      out.write("\t<div id=\"tfheader\">\n");
      out.write("\t\t<form id=\"tfnewsearch\" action = \"book.jsp\"  method=\"post\" ng-init=\"setFirst('");
      out.print(firstchoice);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(secondchoice);
      out.write("');\">\n");
      out.write("\t\t<input type=\"hidden\" name=\"firstchoice\" id=\"firstchoice\" value=\"{{add_first}}\">\n");
      out.write("\t\t<input type=\"hidden\" name=\"secondchoice\" id=\"secondchoice\" value=\"{{add_second.search_id}}\">\n");
      out.write("\t\t<select class=\"city\" ng-model=\"add_first\" ng-options=\"name.search_type as name.search_type for name in firstName\"  ng-change=\"getFirst();\">\n");
      out.write("\t\t</select>\n");
      out.write("\t\t<select class=\"town\" ng-model=\"add_second\" ng-options=\"name as name.search_name for name in setSecondName\" >\n");
      out.write("\t\t</select>\n");
      out.write("\t\t        <input type=\"text\" class=\"tftextinput\"  id = \"bookname\" name = \"bookname\"  size=\"21\" maxlength=\"120\" value=\"");
      out.print(bookname);
      out.write("\">\n");
      out.write("\n");
      out.write("\t\t\t\t<input type=\"submit\" value=\"search\" class=\"tfbutton\">\n");
      out.write("\t\t</form>\n");
      out.write("\t<div class=\"tfclear\"></div>\n");
      out.write("\t  </div>\n");
      out.write("\t  <center>\n");
      out.write("\t  \n");
      out.write("\t\t\n");
      out.write("\t\t<h2 style=\"color:#00b36b\" align=\"center\" ><font face=\"Algerian\">OUR SHOP</font></h2>\n");
      out.write("        <table width=\"90%\" bgcolor=\"#CEF6EC\" border=\"1\" BORDERCOLOR=white style=\"border-collapse: collapse;\" style=\"border: 1px solid black;\">\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t<th>\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<div style=\"float: left;\">\n");
      out.write("\t\t\t\t\t<a href=\"index3.jsp\"><img src=\"pic6.jpg\" alt=\"妙語說書人\" id=\"itemImg\" width=\"200\" height=\"250\"></a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div style=\"float: left;\">\n");
      out.write("\t\t\t\t\t<H2 style=\"color:BLUE;\">妙語說書人(DIXIT)</H2>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">人數：3~6人</p>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">作者：Jean-Louis Roubira</p>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">類別：派對遊戲</p>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">Price: 1200 NTD</p>\n");
      out.write("\t\t\t\t\t<p><a href=\"index3.jsp\" style=\"color:blue;\">MORE</a></p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div style=\"float: none; clear: both;\"></div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<div style=\"float: left;\">\n");
      out.write("\t\t\t\t\t<a href=\"index3-1.jsp\"><img src=\"pic9.jpg\" alt=\"矮人礦坑\" id=\"itemImg\" width=\"200\" height=\"250\"></a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div style=\"float: left;\">\n");
      out.write("\t\t\t\t\t<H2 style=\"color:BLUE;\">矮人礦坑(Saboteur)</H2>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">人數：3~10人</p>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">作者：Frederic Moyersoen</p>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">類別：派對遊戲</p>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">Price: 20 NTD</p>\n");
      out.write("\t\t\t\t\t<p><a href=\"index3-1.jsp\" style=\"color:blue;\">MORE</a></p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div style=\"float: none; clear: both;\"></div>\t\t\t\t\n");
      out.write("</li>\n");
      out.write("<li>\n");
      out.write("    <div style=\"float: left;\">\n");
      out.write("        <a href=\"index3-2.jsp\"><img src=\"pic10.jpg\" alt=\"驢橋\" id=\"itemImg\" width=\"200\" height=\"250\"></a>\n");
      out.write("    </div>\n");
      out.write("    <div style=\"float: left;\">\n");
      out.write("        <H2 style=\"color:BLUE;\">驢橋(Eselsbrücke)</H2>\n");
      out.write("        <p style=\"color:BLACK;\">人數：3~12人</p>\n");
      out.write("        <p style=\"color:BLACK;\">作者：Stefan Dorra & Ralf zur Linde</p>\n");
      out.write("\t\t<p style=\"color:BLACK;\">類別：記憶</p>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">Price: 20 NTD</p>\n");
      out.write("        <p><a href=\"index3-2.jsp\" style=\"color:blue;\">MORE</a></p>\n");
      out.write("    </div>\n");
      out.write("    <div style=\"float: none; clear: both;\"></div>\n");
      out.write("\t\n");
      out.write("</li>\n");
      out.write("</th>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("<table width=\"90%\" bgcolor=\"WHITE\" border=\"1\" BORDERCOLOR=#00b36b style=\"border-collapse: collapse;\" style=\"border: 1px solid black;\">\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t<th>\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<div style=\"float: left;\">\n");
      out.write("\t\t\t\t\t<a href=\"index3-3.jsp\"><img src=\"pic4.jpg\" alt=\"卡卡頌(Carcassonne)\" id=\"itemImg\" width=\"200\" height=\"250\"></a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div style=\"float: left;\">\n");
      out.write("\t\t\t\t\t<H2 style=\"color:BLUE;\">卡卡頌(Carcassonne)</H2>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">人數：2~5人</p>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">作者：Klaus-Jürgen Wrede</p>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">類別：派對遊戲</p>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">Price: 20 NTD</p>\n");
      out.write("\t\t\t\t\t<p><a href=\"index3-3.jsp\" style=\"color:blue;\">MORE</a></p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div style=\"float: none; clear: both;\"></div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<div style=\"float: left;\">\n");
      out.write("\t\t\t\t\t<a href=\"index3-4.jsp\"><img src=\"pic12.jpg\" alt=\"知識線環球旅行篇\" id=\"itemImg\" width=\"200\" height=\"250\"></a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"float: left;\">\n");
      out.write("\t\t\t\t\t<H2 style=\"color:BLUE;\">跑出魔法師(ABRACA)</H2>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">人數：2~5人</p>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">作者：</p>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">類別：派對遊戲</p>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">Price: 20 NTD</p>\n");
      out.write("\t\t\t\t\t<p><a href=\"index3-4.jsp\" style=\"color:blue;\">MORE</a></p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div style=\"float: none; clear: both;\"></div>\n");
      out.write("\t\t\t\t\n");
      out.write("</li>\n");
      out.write("<li>\n");
      out.write("    <div style=\"float: left;\">\n");
      out.write("        <a href=\"index3-5.jsp\"><img src=\"pic14.jpg\" alt=\"驢橋\" id=\"itemImg\" width=\"200\" height=\"250\"></a>\n");
      out.write("    </div>\n");
      out.write("    \t\t\t\t<div style=\"float: left;\">\n");
      out.write("\t\t\t\t\t<H2 style=\"color:BLUE;\">超級犀牛(super rhino)</H2>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">人數：2~5人</p>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">作者：Thies Schwarz</p>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">類別：家庭遊戲</p>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">Price: 20 NTD</p>\n");
      out.write("\t\t\t\t\t<p><a href=\"index3-5.jsp\" style=\"color:blue;\">MORE</a></p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div style=\"float: none; clear: both;\"></div>\n");
      out.write("\t\n");
      out.write("</li>\n");
      out.write("</th>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("<table width=\"90%\" bgcolor=\"#CEF6EC\" border=\"1\" BORDERCOLOR=white style=\"border-collapse: collapse;\" style=\"border: 1px solid black;\">\n");
      out.write("\t\t\t<tr>\n");
      out.write("\t\t\t<th>\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<div style=\"float: left;\">\n");
      out.write("\t\t\t\t\t<a href=\"index3-6.jsp\"><img src=\"pic15.jpg\" alt=\"妙語說書人\" id=\"itemImg\" width=\"200\" height=\"250\"></a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"float: left;\">\n");
      out.write("\t\t\t\t\t<H2 style=\"color:BLUE;\">情書(Love Letter)</H2>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">人數：2~4人</p>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">作者：Seiji Kanai</p>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">類別：家庭遊戲</p>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">Price: 20 NTD</p>\n");
      out.write("\t\t\t\t\t<p><a href=\"index3-6.jsp\" style=\"color:blue;\">MORE</a></p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div style=\"float: none; clear: both;\"></div>\n");
      out.write("\t\t\t\t\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<div style=\"float: left;\">\n");
      out.write("\t\t\t\t\t<a href=\"index3-7.jsp\"><img src=\"pic11.jpg\" alt=\"矮人礦坑\" id=\"itemImg\" width=\"200\" height=\"250\"></a>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t\t\t\t\t<div style=\"float: left;\">\n");
      out.write("\t\t\t\t\t<H2 style=\"color:BLUE;\">拉密(Rummikub)</H2>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">人數：3~4人</p>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">作者：Ephraim Hertzano</p>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">類別：派對遊戲</p>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">Price: 20 NTD</p>\n");
      out.write("\t\t\t\t\t<p><a href=\"index3-7.jsp\" style=\"color:blue;\">MORE</a></p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div style=\"float: none; clear: both;\"></div>\n");
      out.write("\t\t\t\t\n");
      out.write("</li>\n");
      out.write("<li>\n");
      out.write("    <div style=\"float: left;\">\n");
      out.write("        <a href=\"index3-8.jsp\"><img src=\"pic7.jpg\" alt=\"驢橋\" id=\"itemImg\" width=\"200\" height=\"250\"></a>\n");
      out.write("    </div>\n");
      out.write("    \t\t\t\t<div style=\"float: left;\">\n");
      out.write("\t\t\t\t\t<H2 style=\"color:BLUE;\">狂牛衝浪(COWABUNGA)</H2>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">人數：2~5人</p>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">作者：Reinhard Staupe</p>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">類別：派對遊戲</p>\n");
      out.write("\t\t\t\t\t<p style=\"color:BLACK;\">Price: 20 NTD</p>\n");
      out.write("\t\t\t\t\t<p><a href=\"index3-8.jsp\" style=\"color:blue;\">MORE</a></p>\n");
      out.write("\t\t\t\t</div>\n");
      out.write("\t\t\t\t<div style=\"float: none; clear: both;\"></div>\n");
      out.write("\t\n");
      out.write("</li>\n");
      out.write("</th>\n");
      out.write("</tr>\n");
      out.write("</table>\n");
      out.write("\n");
      out.write("</center>\n");
      out.write("<div class=\"container\">\n");
      out.write("  <h2>Pager</h2>\n");
      out.write("  <ul class=\"pager\">\n");
      out.write("    <li><a href=\"index4.jsp\">1</a></li>\n");
      out.write("    <li><a href=\"index4-1.jsp\">2</a></li>\n");
      out.write("\t<li><a href=\"index4-2.jsp\">3</a></li>\n");
      out.write("\t<li><a href=\"index4-3.jsp\">4</a></li>\n");
      out.write("\t<li><a href=\"index4-4.jsp\">5</a></li>\n");
      out.write("\t<li><a href=\"index4-5.jsp\">6</a></li>\n");
      out.write("\t<li><a href=\"index4-6.jsp\">»</a></li>\n");
      out.write("  </ul>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
