/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M4
 * Generated at: 2016-11-14 13:28:31 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;
import teachDB.DbBean;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/_include/menu.jsp", Long.valueOf(1479121096829L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("teachDB.DbBean");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");

String adminID = "";
String adminPW = "";

String act = request.getParameter("act");
String admin_ip  =request.getRemoteAddr();
String rand = (String)session.getAttribute("rand");
	String input = request.getParameter("rand");

if ( act != null ) {
	if ( act.equals("process") ) {
		try {
			adminID = request.getParameter("adminID").trim();
			adminPW = request.getParameter("adminPW").trim();
			boolean checkip = false;
			DbBean db = new DbBean();
				List iplist = db.SelectRS("select ipaddress from adminfilter where deleteflag = 0 ");				
				if( iplist != null && iplist.size() > 0 ) {
					for ( int i = 0; i < iplist.size(); i++ ) {
						Map ipmap = (Map)iplist.get(i); 
						if( ipmap.get("ipaddress").toString().equals(admin_ip) ) {
							checkip = true;
						}else{
							out.println("<script>alert('未授權');top.location.href='/';</script>");
						}			
					} 
				}else{
					checkip = true;
				}
				if(checkip){
					List loginList = new ArrayList();
					loginList.add(adminID);
					loginList.add(adminPW);
					List userlist = db.SelectRSwhere("select * from member where member_account=? and password = ?",loginList);
					
					if ( userlist != null && userlist.size()>0 && rand.equals(input)) { 
						for ( int i = 0; i < userlist.size(); i++ ) {
							Map usermap = (Map)userlist.get(i); 
								session.setAttribute ("member_id",usermap.get("member_id").toString());
								session.setAttribute ("member_name",usermap.get("member_name").toString());
								session.setAttribute ("member_email",usermap.get("member_email").toString());
						}
						session.setAttribute ("member_account",adminID);
						response.sendRedirect ("/");
						return;
					} else {
						if(!rand.equals(input)){
							out.println ("<script language='javascript'>alert('驗證碼輸入錯誤.');location.href='/login.jsp';</script><noscript>Your browser does not support Script!</noscript>");
						}else{
							out.println ("<script language='javascript'>alert('帳號或密碼錯誤.');location.href='/login.jsp';</script><noscript>Your browser does not support Script!</noscript>");
						}
						return;
					}
				}
			
		} catch ( Exception e ) {
			out.println ("<script language='javascript'>alert('非法存取.');location.href='/';</script><noscript>Your browser does not support Script!</noscript>");
			return;
		}
	}
}

      out.write("\n");
      out.write("<html  ng-app=\"app\" ng-controller= \"mainCrtl\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"utf-8\">\n");
      out.write("      <meta http-equiv=\"X-UA-Compatible\" content=\"IE=edge\">\n");
      out.write("      <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\n");
      out.write("      <title>login</title>\n");
      out.write("\t   <script src=\"https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js\"></script>\n");
      out.write("\t<script src=\"js/jquery.easing.1.3.js\"></script>\n");
      out.write("\t<script src=\"js/jquery.backgroundPosition.js\"></script>\n");
      out.write("\t<script src=\"js/cs.js\"></script>\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css\">\n");
      out.write("    <link rel=\"stylesheet\" href=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap-theme.min.css\">\n");
      out.write("    <script src=\"https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/js/bootstrap.min.js\"></script>\n");
      out.write("    <link rel=\"stylesheet\" href=\"../bootstrap-3.3.1-dist/dist/fonts/\">\n");
      out.write("\t<link href=\"style.css\" rel=\"stylesheet\" type=\"text/css\">\n");
      out.write("\t<script src=\"js/angular.js\"></script>\n");
      out.write("\t<script src=\"js/address.js\"></script>\n");
      out.write("</head>\n");
      out.write("\n");
      out.write(" <body  bgcolor=\"#FFFCA7\"  >\n");
      out.write("\n");
      out.write(" <center>\n");
      out.write(" <table>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t<p style=\"color:#088A85\" align=\"center\" ><font face=\"Algerian\" size=\"250\">GAMEBOARD WORLD</font><a href=\"https://www.facebook.com/%E5%A4%A9%E5%A4%A9%E5%AD%B8%E6%A1%8C%E9%81%8A-1118376901610135/\"  target=\"_blank\" ><img src=\"fb.png\" style=\"width:50px;height:40px;\" align=\"right\"></a>\n");
      out.write("\t\t<a href=\"https://www.facebook.com/%E5%A4%A9%E5%A4%A9%E5%AD%B8%E6%A1%8C%E9%81%8A-1118376901610135/\"  target=\"_blank\" ><img src=\"in.png\" style=\"width:50px;height:40px;\" align=\"right\"></a></p>\n");
      out.write("\t\t<hr>\n");
      out.write("\t\t\t\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t");
      out.write("\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<style >\n");
      out.write("h1 {\n");
      out.write("    font-size: 700%;\n");
      out.write("\t\n");
      out.write("}\n");
      out.write("ul {\n");
      out.write("    list-style-type: none;\n");
      out.write("    margin: 0;\n");
      out.write("    padding: 0;\n");
      out.write("    overflow: hidden;\n");
      out.write("    background-color: #0B615E;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li {\n");
      out.write("\n");
      out.write("    float: left;\n");
      out.write("    border-right:1px solid #bbb;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li:last-child {\n");
      out.write("    border-right: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li a {\n");
      out.write("    display: block;\n");
      out.write("    color: white;\n");
      out.write("    text-align: center;\n");
      out.write("    padding: 14px 16px;\n");
      out.write("    text-decoration: none;\n");
      out.write("}\n");
      out.write("\n");
      out.write("li a:hover:not(.active) {\n");
      out.write("    background-color: #111;\n");
      out.write("}\n");
      out.write("\n");
      out.write(".active {\n");
      out.write("    background-color: #4CAF50;\n");
      out.write("}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<center>\n");
      out.write("<table style=\"border: 0px solid #0B614B;\" style=\"width:100%\">\n");
      out.write("\t<tr>\n");
      out.write("\t<th>\n");
      out.write("\t<image src=LOGODC2.png width=\"100px\" height=\"90\">\n");
      out.write("\t</th>\n");
      out.write("\t\t<th>\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\t\t\t<ul>\n");
      out.write("\t\t\t\t  \n");
      out.write("\t\t\t\t  <li><a class=\"active\" href=\"index.jsp\" target=\"_self\">Home</a></li>\n");
      out.write("\t\t\t\t  <li><a href=\"index4.jsp\" target=\"_self\">Shop</a></li>\n");
      out.write("\t\t\t\t  <li><a href=\"book.jsp\" target=\"_self\">Order</a></li>\n");
      out.write("\t\t\t\t  \n");
      out.write("\t\t\t\t  <li><a href=\"contact.jsp\" target=\"_self\">Contact us</a></li>\n");
      out.write("\t\t\t\t  <li><a href=\"video.jsp\" target=\"_self\">Video</a></li>\n");
      out.write("\t\t\t\t  <li class=\"m-5\"><a href=\"rent.jsp\" target=\"_self\">Status</a></li>\n");
      out.write("\t\t\t\t  <li style=\"float:right\"><a href=\"register.jsp\" target=\"_self\">Sign up</a></li>\n");
      out.write("\t\t\t\t  <li class=\"m-7\"><a href=\"login.jsp\" target=\"_self\">\n");
      out.write("\t\t\t\t");
	if ( session.getAttribute ("member_name") != null) {
      out.write("\n");
      out.write("\t\t\t\tMODIFY\n");
      out.write("\t\t\t\t");
} else {
      out.write("\n");
      out.write("\t\t\t\tSign in\n");
      out.write("\t\t\t\t");
}
      out.write("\n");
      out.write("\t\t\t\t</a></li>\n");
      out.write("\t\t\t\t");
	if ( session.getAttribute ("member_name") != null) {
      out.write("\n");
      out.write("\t\t\t\t<li class=\"m-8\"><a href=\"logout.jsp\" target=\"_self\">Log out</a></li>\n");
      out.write("\t\t\t\t");
}
      out.write("\n");
      out.write("\t\t\t</ul>\n");
      out.write("\t\t\t\t\n");
      out.write("        \n");
      out.write("\n");
      out.write("</th>\n");
      out.write("</table>\n");
      out.write("</center>\n");
      out.write("</body>\n");
      out.write("</html>");
      out.write("\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t</table></center>\n");
      out.write("<div class=\"row\">\n");
      out.write("<div class=\"col-md-4\"></div>\n");
      out.write("<div class=\"col-md-4\">\n");
 if ( session.getAttribute ("member_id") != null) {
	DbBean db = new DbBean();
	int m_id = Integer.parseInt((String)session.getAttribute ("member_id"));
	List idList = new ArrayList();
					idList.add(m_id);
	List memberlist = db.SelectRSwhere("select * from member where member_id=? ",idList);
	if ( memberlist != null && memberlist.size()>0 ) { 
			for ( int i = 0; i < memberlist.size(); i++ ) {
				Map membermap = (Map) memberlist.get(i); 	
			        	String member_account =(String)membermap.get("member_account");
						String member_name    =(String)membermap.get("member_name");
						String member_email   =(String)membermap.get("member_email");
						String password       =(String)membermap.get("password");
						String city           =(String)membermap.get("city");
						String town           =(String)membermap.get("town");
						String address        =(String)membermap.get("address");
						String telephone      =(String)membermap.get("telephone");	
							
	
      out.write("\n");
      out.write("<form id=\"member_form\" class=\"form-horizontal\" role=\"form\" data-ng-init=\"setcity('");
      out.print(city);
      out.write('\'');
      out.write(',');
      out.write('\'');
      out.print(town);
      out.write("');\">\n");
      out.write("<input type=\"hidden\" name=\"member_id\" id=\"member_id\" value=\"");
      out.print(m_id);
      out.write("\">\n");
      out.write("<input type=\"hidden\" name=\"city\" id=\"city\" value=\"{{add_city}}\">\n");
      out.write("<input type=\"hidden\" name=\"town\" id=\"town\" value=\"{{add_town.town}}\">\n");
      out.write("<input type=\"hidden\" name=\"choose\" id=\"choose\" value=\"update\">\n");
      out.write("<table class=\"table table-hover\">\n");
      out.write("<caption>MEMBER MODIFY</caption>\n");
      out.write("\n");
      out.write("<tr>\n");
      out.write("<td>name</td>\n");
      out.write("<td><input type=\"text\" class=\"form-control\" name=\"member_name\" id=\"member_name\" value=\"");
      out.print(member_name);
      out.write("\"> </td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("<td>account</td>\n");
      out.write("<td> <input type=\"text\" class=\"form-control\" name=\"member_account\" id=\"member_account\" value=\"");
      out.print(member_account);
      out.write("\"></td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("<td>password</td>\n");
      out.write("<td><input type=\"text\" class=\"form-control\" name=\"password\" id=\"password\" value=\"");
      out.print(password);
      out.write("\"> </td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("<td>email</td>\n");
      out.write("<td><input type=\"text\" class=\"form-control\" name=\"member_email\" id=\"member_email\" value=\"");
      out.print(member_email);
      out.write("\"> </td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("<td>city</td>\n");
      out.write("<td><select class=\"city\" ng-model=\"add_city\" ng-options=\"name.city as name.city for name in cityName\"  ng-change=\"getcitytown()\">\n");
      out.write("</select> </td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("<td>town</td>\n");
      out.write("<td><select class=\"town\" ng-model=\"add_town\" ng-options=\"name as name.town for name in setTownName\">\n");
      out.write("</select></td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("<td>address</td>\n");
      out.write("<td><input type=\"text\" class=\"form-control\" name=\"address\" id=\"address\" value=\"");
      out.print(address);
      out.write("\"> </td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("<td>telephone</td>\n");
      out.write("<td><input type=\"text\" class=\"form-control\" name=\"telephone\" id=\"telephone\" value=\"");
      out.print(telephone);
      out.write("\"> </td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("<td>\n");
      out.write("<input type = \"button\" id = \"modify_submit\" class=\"btn btn-info\" value = \"MODIFY\" onclick=\"form_submit();\" >\n");
      out.write("</td>\n");
      out.write("</tr>\n");
      out.write("</tr>\t\n");
      out.write("</table>\t\n");
      out.write("</form>\n");
 		}
	}
} else {

      out.write("\n");
      out.write("\n");
      out.write("<table class=\"table table-hover\" width=\"500\">\n");
      out.write("\n");
      out.write("<caption><STRONG>MEMBER</STRONG></caption>\n");
      out.write(" <form id=\"frmAdminLogin1\" onsubmit='return isAdminLogin(1)'>\n");
      out.write("<tr>\n");
      out.write("<td>account</td>\n");
      out.write("<td> <input type=\"text\" class=\"form-control\" name =\"login_account\" id = \"login_account\" value=\"\"></td>\n");
      out.write("</tr>\n");
      out.write("</form>\n");
      out.write("<form id=\"frmAdminLogin2\" action=\"\" onsubmit='return isAdminLogin(2)' method=\"post\">\n");
      out.write("                        <input type=\"hidden\" name=\"act\" value=\"process\">\n");
      out.write("                        <input type=\"hidden\" name=\"adminID\">\n");
      out.write("<tr>\n");
      out.write("<td>password</td>\n");
      out.write("<td><input type=\"password\" class=\"form-control\" name =\"adminPW\"> </td>\n");
      out.write("</tr>\n");
      out.write("<tr>\n");
      out.write("<td><img border=0 src=\"/@admin/image.jsp\"  width=\"94\" heigh=\"34\" border=\"0\"></td>\n");
      out.write("<td><input type=\"password\" class=\"form-control\" name =\"rand\" maxlength=\"4\" placeholder=\"請輸入驗證碼\" onKeyDown=\"toQuery()\"> </td>\n");
      out.write("</tr>\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t<td><p>Not a member? <a href=\"register.jsp\">Register</a></p></td>\n");
      out.write("\t\t<td><input type = \"button\" class=\"btn btn-info\" value = \"LOGIN\"  onclick='submitAdminLogin()'></td>\n");
      out.write("\t\t\n");
      out.write("\t\t</tr>\n");
      out.write("</form>\t\t\n");
      out.write("</tr>\t\n");
      out.write("</table>\t\n");
 } 
      out.write("\n");
      out.write("</div>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("<script language='javascript'>\n");
      out.write("    function isAdminLogin (n) {\n");
      out.write("        var f1 = document.getElementById(\"frmAdminLogin1\");\n");
      out.write("        var f2 = document.getElementById(\"frmAdminLogin2\");\n");
      out.write("        f2.adminID.value = document.getElementById(\"login_account\").value;\n");
      out.write("\n");
      out.write("        if (n == 1) {\n");
      out.write("            if (document.getElementById(\"login_account\").value == \"\") {\n");
      out.write("                alert (\"請輸入帳號.\");\n");
      out.write("                return false;\n");
      out.write("            } else {\n");
      out.write("                f2.adminPW.focus ();\n");
      out.write("                return false;\n");
      out.write("            }\n");
      out.write("\n");
      out.write("        } else if (n == 2) {\n");
      out.write("            if (f2.adminID.value == \"\") {\n");
      out.write("                alert (\"請輸入帳號.\");\n");
      out.write("                document.getElementById(\"login_account\").focus ();\n");
      out.write("                return false;\n");
      out.write("            } else {\n");
      out.write("                if (f2.adminPW.value == \"\") {\n");
      out.write("                    alert (\"請輸入密碼.\");\n");
      out.write("                    f2.adminPW.focus ();\n");
      out.write("                    return false;\n");
      out.write("                } else {\n");
      out.write("                    return true;\n");
      out.write("                }\n");
      out.write("            }\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    function submitAdminLogin () {\n");
      out.write("        if (!isAdminLogin(2)) return;\n");
      out.write("        else {\n");
      out.write("            frmAdminLogin2.submit ();\n");
      out.write("        }\n");
      out.write("    }\n");
      out.write("\tfunction toQuery(){\n");
      out.write("\t\tif( event.keyCode == 13 ){\n");
      out.write("\t\t\tsubmitAdminLogin();\n");
      out.write("\t\t}\n");
      out.write("\t}\n");
      out.write("\tfunction form_submit() {\n");
      out.write("\n");
      out.write("    var msg = '';\n");
      out.write("   \n");
      out.write("    if ($('#member_name').val().length == 0)\n");
      out.write("        msg += '沒有填寫 \"name\"\\n';\n");
      out.write("    else if ($('#member_name').val().length < 2)\n");
      out.write("        msg += '\"name\"請填寫詳細\\n';\n");
      out.write("\t\n");
      out.write("\t if ($('#member_account').val().length == 0)\n");
      out.write("        msg += '沒有填寫 \"account\"\\n';\n");
      out.write("    else if ($('#member_account').val().length < 4)\n");
      out.write("        msg += '\"account\"至少4個字母\\n';\n");
      out.write("\t\n");
      out.write("\t if ($('#password').val().length == 0)\n");
      out.write("        msg += '沒有填寫 \"password\"\\n';\n");
      out.write("    else if ($('#password').val().length < 4)\n");
      out.write("        msg += '\"password\"至少4個字母\\n';\n");
      out.write("\t\n");
      out.write("\t if ($('#member_email').val().length == 0)\n");
      out.write("        msg += '沒有填寫 \"E-mail\"\\n';\n");
      out.write("    else if (/^[\\w-]+(\\.[\\w-]+)*@[\\w-]+(\\.[\\w-]+)+$/.test($('#member_email').val()) === false)\n");
      out.write("        msg += '格式有誤 \"E-mail\"\\n';\n");
      out.write("\n");
      out.write("\t if ($('#address').val().length == 0)\n");
      out.write("        msg += '沒有填寫 \"address\"\\n';\n");
      out.write("    else if ($('#address').val().length < 5)\n");
      out.write("        msg += '\"address\"至少5個字\\n';\n");
      out.write("\t\n");
      out.write("    if ($('#telephone').val().length == 0)\n");
      out.write("        msg += '沒有填寫 \"telephone\"\\n';\n");
      out.write("    else if (/\\d{10,}/.test($('#telephone').val()) === false)\n");
      out.write("        msg += '格式有錯 \"telephone\"\\n';  \n");
      out.write("   \n");
      out.write("   \n");
      out.write("    if (msg.length == 0){\n");
      out.write("\t\t$('#modify_submit').attr('disabled', true);\n");
      out.write("        $.ajax({\n");
      out.write("            url: \"/controller/MemberHandler.jsp\",\n");
      out.write("            data:$(\"#member_form\").serialize(),\n");
      out.write("            type: \"POST\",\n");
      out.write("            dataType: \"json\",\n");
      out.write("            success: function(data,textStatus,jqXHR) {\n");
      out.write("            \tconsole.log(data);\n");
      out.write("            \tconsole.log(textStatus);\n");
      out.write("            \tconsole.log(jqXHR);\n");
      out.write("            \tif(data == 2){\n");
      out.write("\t\t\t\t\tconsole.log('會員資料修改成功');\n");
      out.write("            \t\talert($('#member_name').val() + '的會員資料已修改成功。');\n");
      out.write("\t\t\t\t\tlocation.reload();\n");
      out.write("\t\t\t\t}else if(data == 4){\n");
      out.write("\t\t\t\t\tvar f3 = document.getElementById(\"member_form\");\n");
      out.write("\t\t\t\t\t alert(\"此帳號\" + $('#member_account').val() + \"已有人使用，請換帳號，謝謝。\");\n");
      out.write("\t\t\t\t\t $('#member_account').val(\"\");\n");
      out.write("\t\t\t\t\t   f3.member_account.focus ();\n");
      out.write("            \t}else{\n");
      out.write("            \t\talert('系統錯誤，請通知網站管理員');\n");
      out.write("            \t}\n");
      out.write("            },\n");
      out.write("            error: function(XMLHttpRequest, textStatus, errorThrown) {\n");
      out.write("            \tconsole.log('會員資料修改失敗');\n");
      out.write("            \tconsole.log(\"XMLHttpRequest.status=\"+XMLHttpRequest.status+\n");
      out.write("\t\t\t    \t\t\"\\nXMLHttpRequest.readyState=\"+XMLHttpRequest.readyState+\"\\ntextStatus=\"+textStatus+\"\\errorThrown=\"+errorThrown);\n");
      out.write("            },\n");
      out.write("            complete: function(XMLHttpRequest) {\n");
      out.write("\t\t\t\t$('#modify_submit').attr('disabled', false);\n");
      out.write("            \tconsole.log('會員資料修改結果');\n");
      out.write("            \tconsole.log(XMLHttpRequest);\n");
      out.write("            }\n");
      out.write("            \n");
      out.write("        \t});\n");
      out.write("    }\n");
      out.write("    else{\n");
      out.write("        alert(msg);\n");
      out.write("    }\n");
      out.write("\n");
      out.write("    return false;\n");
      out.write("}\n");
      out.write("</script>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
