/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M4
 * Generated at: 2016-05-31 14:50:42 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Map;
import teachDB.DbBean;

public final class main_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("teachDB.DbBean");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<html>\n");
      out.write("\n");
      out.write("<body  bgcolor=\"#FFFCA7\"> \n");
      out.write("\t\t<table style=\"width:100%\" style=\"high:30%\" background=\"logo.jpg\">\n");
      out.write("\t\t<tr>\n");
      out.write("\t\t\t<td height=\"200\" align=\"center\" ><font color=\"black\" size=1000>看啥租啥</font></td>\n");
      out.write("\t\t</tr>\n");
      out.write("\t\t</table>\n");
      out.write("<meta name=\"ROBOTS\" content=\"NOINDEX, NOFOLLOW\" />\n");
      out.write("<!-- CSS styles for standard search box -->\n");
      out.write("<style type=\"text/css\">\n");
      out.write("\t#tfheader{\n");
      out.write("\t\tbackground-color:#c3dfef;\n");
      out.write("\t}\n");
      out.write("\t#tfnewsearch{\n");
      out.write("\t\tfloat:right;\n");
      out.write("\t\tpadding:20px;\n");
      out.write("\t}\n");
      out.write("\t.tftextinput{\n");
      out.write("\t\tmargin: 0;\n");
      out.write("\t\tpadding: 5px 15px;\n");
      out.write("\t\tfont-family: Arial, Helvetica, sans-serif;\n");
      out.write("\t\tfont-size:14px;\n");
      out.write("\t\tborder:1px solid #0076a3; border-right:0px;\n");
      out.write("\t\tborder-top-left-radius: 5px 5px;\n");
      out.write("\t\tborder-bottom-left-radius: 5px 5px;\n");
      out.write("\t}\n");
      out.write("\t.tfbutton {\n");
      out.write("\t\tmargin: 0;\n");
      out.write("\t\tpadding: 5px 15px;\n");
      out.write("\t\tfont-family: Arial, Helvetica, sans-serif;\n");
      out.write("\t\tfont-size:14px;\n");
      out.write("\t\toutline: none;\n");
      out.write("\t\tcursor: pointer;\n");
      out.write("\t\ttext-align: center;\n");
      out.write("\t\ttext-decoration: none;\n");
      out.write("\t\tcolor: #ffffff;\n");
      out.write("\t\tborder: solid 1px #0076a3; border-right:0px;\n");
      out.write("\t\tbackground: #0095cd;\n");
      out.write("\t\tbackground: -webkit-gradient(linear, left top, left bottom, from(#00adee), to(#0078a5));\n");
      out.write("\t\tbackground: -moz-linear-gradient(top,  #00adee,  #0078a5);\n");
      out.write("\t\tborder-top-right-radius: 5px 5px;\n");
      out.write("\t\tborder-bottom-right-radius: 5px 5px;\n");
      out.write("\t}\n");
      out.write("\t.tfbutton:hover {\n");
      out.write("\t\ttext-decoration: none;\n");
      out.write("\t\tbackground: #007ead;\n");
      out.write("\t\tbackground: -webkit-gradient(linear, left top, left bottom, from(#0095cc), to(#00678e));\n");
      out.write("\t\tbackground: -moz-linear-gradient(top,  #0095cc,  #00678e);\n");
      out.write("\t}\n");
      out.write("\t/* Fixes submit button height problem in Firefox */\n");
      out.write("\t.tfbutton::-moz-focus-inner {\n");
      out.write("\t  border: 0;\n");
      out.write("\t}\n");
      out.write("\t.tfclear{\n");
      out.write("\t\tclear:both;\n");
      out.write("\t}\n");
      out.write("</style>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<!-- HTML for SEARCH BAR -->\n");
      out.write("\t<div id=\"tfheader\">\n");
      out.write("\t\t<form id=\"tfnewsearch\" method=\"get\" action=\"http://www.google.com\">\n");
      out.write("\t\t\t<select>\n");
      out.write("\t\t\t  <option value=\"happy\">Happy</option>\n");
      out.write("\t\t\t  <option value=\"sad\">Sad</option>\n");
      out.write("\t\t\t  <option value=\"freetime\">Free-time</option>\n");
      out.write("\t\t\t  <option value=\"travel\">Travel</option>\n");
      out.write("\t\t\t  <option value=\"cook\">Cook</option>\n");
      out.write("\t\t\t  <option value=\"love\">Love</option>\n");
      out.write("\t\t\t</select>\n");
      out.write("\t\t        <input type=\"text\" class=\"tftextinput\" name=\"q\" size=\"21\" maxlength=\"120\"><input type=\"submit\" value=\"search\" class=\"tfbutton\">\n");
      out.write("\t\t</form>\n");
      out.write("\t<div class=\"tfclear\"></div>\n");
      out.write("\t</div>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<style type=\"text/css\">\n");
      out.write("<!--\n");
      out.write(".style3 {color: #FF0000; font-weight: bold; }\n");
      out.write("-->\n");
      out.write("</style>\n");
      out.write("<h3 align=\"center\">New Book</h3>\n");
      out.write("<table border=\"0\" cellspacing=\"1\" cellpadding=\"0\" width=\"100%\">\n");
      out.write("  <tr>\n");
      out.write("    <td width=\"10\" valign=\"top\"><p>1.</p></td>\n");
      out.write("    <td width=\"140\" valign=\"top\"><p><a href=\"confirm.html\"><img border=\"0\" width=\"140\" height=\"190\" src=\"pic1.jpg\" alt=\"bvcb\" /></a></p></td>\n");
      out.write("    <td valign=\"top\"><table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"100%\">\n");
      out.write("      <tr>\n");
      out.write("        <td colspan=\"2\"><h3>經濟學原理:全彩圖解</h3>\n");
      out.write("              <p>出版社：海鴿文化</p></td>\n");
      out.write("      </tr>\n");
      out.write("      <tr>\n");
      out.write("        <td colspan=\"2\"><p>作者：阿爾弗雷德.馬歇爾(Alfred Marshall)著;賈開吉譯</p></td>\n");
      out.write("      </tr>\n");
      out.write("      <tr>\n");
      out.write("        <td colspan=\"2\"><p>&nbsp;</p></td>\n");
      out.write("      </tr>\n");
      out.write("      <tr>\n");
      out.write("        <td colspan=\"2\"><table border=\"0\" cellspacing=\"1\" cellpadding=\"0\" width=\"100%\">\n");
      out.write("          <tr>\n");
      out.write("            <td><p>出版年：2014[民103]</p></td>\n");
      out.write("            <td><p>&nbsp;</p></td>\n");
      out.write("          </tr>\n");
      out.write("        </table></td>\n");
      out.write("      </tr>\n");
      out.write("      <tr>\n");
      out.write("        <td colspan=\"2\"><p>&nbsp;</p></td>\n");
      out.write("      </tr>\n");
      out.write("      <tr>\n");
      out.write("        <td><p>Price: <span class=\"style3\">300</span> NTD</p>\n");
      out.write("\t\t<form action=\"confirm.html\">\n");
      out.write("\t\t<input type=\"submit\" value=\"Order\">\n");
      out.write("\t\t</form>\n");
      out.write("\t\t</td>\n");
      out.write("\t\t\n");
      out.write("      </tr>\n");
      out.write("    </table></td>\n");
      out.write("\t\n");
      out.write("  </tr>\n");
      out.write("  <tr>\n");
      out.write("    <td colspan=\"3\"><p>&nbsp;</p></td>\n");
      out.write("  </tr>\n");
      out.write("  <tr>\n");
      out.write("    <td colspan=\"3\"><p>&nbsp;</p></td>\n");
      out.write("  </tr>\n");
      out.write("  <tr>\n");
      out.write("    <td width=\"10\" valign=\"top\"><p>2.</p></td>\n");
      out.write("    <td width=\"140\" valign=\"top\"><p><a href=\"confirm.html\"><img border=\"0\" width=\"140\" height=\"190\" src=\"pic2.jpg\" alt=\"cvbcv\" /></a></p></td>\n");
      out.write("    <td valign=\"top\"><table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"100%\">\n");
      out.write("      <tr>\n");
      out.write("        <td colspan=\"2\"><h3>20天衝刺新多益拿高分[有聲書]</h3>\n");
      out.write("              <p>出版社：人類智庫數位科技</p></td>\n");
      out.write("      </tr>\n");
      out.write("      <tr>\n");
      out.write("        <td colspan=\"2\"><p>作者：元晶瑞, 鄭然澤著</p></td>\n");
      out.write("      </tr>\n");
      out.write("      <tr>\n");
      out.write("        <td colspan=\"2\"><p>&nbsp;</p></td>\n");
      out.write("      </tr>\n");
      out.write("      <tr>\n");
      out.write("        <td colspan=\"2\"><table border=\"0\" cellspacing=\"1\" cellpadding=\"0\" width=\"100%\">\n");
      out.write("          \n");
      out.write("          <tr>\n");
      out.write("            <td><p>出版地：新北市</p></td>\n");
      out.write("            <td><p>&nbsp;</p></td>\n");
      out.write("          </tr>\n");
      out.write("        </table></td>\n");
      out.write("      </tr>\n");
      out.write("      <tr>\n");
      out.write("        <td colspan=\"2\"><p>&nbsp;</p></td>\n");
      out.write("      </tr>\n");
      out.write("      <tr>\n");
      out.write("        <td><p>Price: <span class=\"style3\">500</span> NTD</p>\n");
      out.write("\t\t<form action=\"confirm.html\">\n");
      out.write("\t\t<input type=\"submit\" value=\"Order\">\n");
      out.write("\t\t</form>\n");
      out.write("\t\t</td>\n");
      out.write("      </tr>\n");
      out.write("    </table></td>\n");
      out.write("  </tr>\n");
      out.write("  <tr>\n");
      out.write("    <td colspan=\"3\"><p>&nbsp;</p></td>\n");
      out.write("  </tr>\n");
      out.write("  <tr>\n");
      out.write("    <td colspan=\"3\"><p>&nbsp;</p></td>\n");
      out.write("  </tr>\n");
      out.write("  <tr>\n");
      out.write("    <td width=\"10\" valign=\"top\"><p>3.</p></td>\n");
      out.write("    <td width=\"140\" valign=\"top\"><p><a href=\"confirm.html\"><img border=\"0\" width=\"140\" height=\"190\" src=\"pic3.jpg\" alt=\"bvcbcv\" /></a></p></td>\n");
      out.write("    <td valign=\"top\"><table border=\"0\" cellspacing=\"0\" cellpadding=\"0\" width=\"100%\">\n");
      out.write("      <tr>\n");
      out.write("        <td colspan=\"2\"><h3>自助旅行不求人!iPhone手機旅遊萬事通 </h3>\n");
      out.write("              <p>出版社：博碩文化</p></td>\n");
      out.write("      </tr>\n");
      out.write("      <tr>\n");
      out.write("        <td colspan=\"2\"><p>作者：酆士昌著</p></td>\n");
      out.write("      </tr>\n");
      out.write("      <tr>\n");
      out.write("        <td colspan=\"2\"><p>&nbsp;</p></td>\n");
      out.write("      </tr>\n");
      out.write("      <tr>\n");
      out.write("        <td colspan=\"2\"><table border=\"0\" cellspacing=\"1\" cellpadding=\"0\" width=\"100%\">\n");
      out.write("          \n");
      out.write("          <tr>\n");
      out.write("            <td><p>出版年：2013[民102]</p></td>\n");
      out.write("            <td><p>&nbsp;</p></td>\n");
      out.write("          </tr>\n");
      out.write("        </table></td>\n");
      out.write("      </tr>\n");
      out.write("      <tr>\n");
      out.write("        <td colspan=\"2\"><p>&nbsp;</p></td>\n");
      out.write("      </tr>\n");
      out.write("      \n");
      out.write("      <tr>\n");
      out.write("        <td><p>Price: <span class=\"style3\">400</span> NTD</p>\n");
      out.write("\t\t<form action=\"confirm.html\">\n");
      out.write("\t\t<input type=\"submit\" value=\"Order\">\n");
      out.write("\t\t</form>\n");
      out.write("\t\t</td>\n");
      out.write("      </tr>\n");
      out.write("    </table></td>\n");
      out.write("  </tr>\n");
      out.write("  <tr>\n");
      out.write("    <td colspan=\"3\"><p>&nbsp;</p></td>\n");
      out.write("  </tr>\n");
      out.write("  <tr>\n");
      out.write("    <td colspan=\"3\"><p>&nbsp;</p></td>\n");
      out.write("  </tr>\n");
      out.write("</table>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
