/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M4
 * Generated at: 2016-11-11 13:28:16 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.__0040admin;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class admin_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/_include/lib_admin.jsp", Long.valueOf(1466632534000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    java.lang.Throwable exception = org.apache.jasper.runtime.JspRuntimeLibrary.getThrowable(request);
    if (exception != null) {
      response.setStatus(javax.servlet.http.HttpServletResponse.SC_INTERNAL_SERVER_ERROR);
    }
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<style type=\"text/css\">\n");
      out.write("body { background:#E0E0E0;}\n");
      out.write("td   { font-size:12px; color:#ffffff; }\n");
      out.write("a    { color:#ffffff; text-decoration:none; }\n");
      out.write("a:hover { text-decoration:underline; }\n");
      out.write("b\t{color:#A0A0A0}\n");
      out.write(".arrow{\n");
      out.write("\tposition:absolute;\n");
      out.write("\twidth:33px;\n");
      out.write("\theight:38px;\n");
      out.write("\tz-index:111;\n");
      out.write("\tleft:500px;\n");
      out.write("\ttop:50px;\n");
      out.write("\tcursor:pointer;\n");
      out.write("\t-webkit-transition: -webkit-transform 0.4s ease !important;\n");
      out.write("\t-moz-transition: -webkit-transform 0.4s ease !important;\n");
      out.write("\t-ms-transition: -webkit-transform 0.4s ease !important;\n");
      out.write("\ttransition: transform 0.4s ease !important;\t\n");
      out.write("}\n");
      out.write(".opacity{\n");
      out.write("\topacity:.5;\n");
      out.write("}\n");
      out.write(".rotate{\t\n");
      out.write("\ttransform:rotate(180deg);\t\n");
      out.write("}\n");
      out.write(".close{\n");
      out.write("\t-webkit-transform:translateY(-60px);\n");
      out.write("\t-moz-transform:translateY(-60px);\n");
      out.write("\t-ms-transform:translateY(-60px);\n");
      out.write("\ttransform:translateY(-60px);\t\n");
      out.write("}\n");
      out.write("\n");
      out.write("</style>\n");
      out.write('\n');

if ( session.getAttribute ("sesAdminID") == null || session.getAttribute ("sesAdminID").equals ( "" ) ) {
	out.println ("<script language='javascript'>alert('您需重新登入.'); if (parent.window) { parent.window.location.href='/@admin'; } else { location.href='/@admin'; } </script>");
	return;
}

      out.write('\n');
	
	String admin_ip  =request.getRemoteAddr();
	String sesAdminName = (String)session.getAttribute ("sesAdminName");
	String MainAdmin = (String)session.getAttribute ("sesMainAdmin");
	String adminID = (String)session.getAttribute ("sesAdminID");
	String adminName = (String)session.getAttribute ("sesAdminName"); 
	int sum = 0;

      out.write("\n");
      out.write("<link rel=\"stylesheet\" href=\"style.css\" type=\"text/css\" />\n");
      out.write("<script type=\"text/javascript\" src=\"script.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"/js/jquery-1.11.1.min.js\"></script>\t\n");
      out.write("<body >\n");
      out.write("<nav>\n");
      out.write("\t<div style=\"top:0px;left:0px;height:70px;background-color:#000000;\">\n");
      out.write("\t\t<div style=\"float:left\"><img src=\"avatar.jpg\" style=\"width:75px;height:70px;\"></div>\n");
      out.write("\t\t\t<div ><font size=\"5\" color=\"yellow\" >目前使用者:");
      out.print(sesAdminName);
      out.write("  IP:");
      out.print(admin_ip);
      out.write("</font></div>\n");
      out.write("\t\t\t\n");
      out.write("\t<ul class=\"menu\" id=\"menu\">\n");
      out.write("\t<li><a href=\"logout.jsp\" class=\"menulink\">登出管理者</a></li>\n");
      out.write("\t");
if(MainAdmin.equals("1")){
      out.write("\n");
      out.write("\t<li><a href=\"#\" class=\"menulink\">後台使用者資訊及管理</a>\n");
      out.write("\t\t<ul>\t\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"sub\">使用者</a>\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li class=\"topline\"><a href='adminuser.jsp' target='incFrame'>管理使用者</a></li>\n");
      out.write("\t\t\t\t\t<li><a href='adminfilter.jsp' target='incFrame' >限制IP登入後台</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t\t<li><a href='contact_form.jsp' target='incFrame' >客戶訊息查詢</a></li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t</li>\n");
      out.write("\t");
}
      out.write("\n");
      out.write("\t<li>\n");
      out.write("\t\t<a href='newslist.jsp' target='incFrame'  class=\"menulink\">最新消息管理</a>\n");
      out.write("\t</li>\n");
      out.write("\t<li><a href=\"#\" class=\"menulink\">桌遊項目管理</a>\n");
      out.write("\t\t<ul>\t\n");
      out.write("\t\t\t<li>\n");
      out.write("\t\t\t\t<a href=\"#\" class=\"sub\">類別及推薦管理</a>\n");
      out.write("\t\t\t\t<ul>\n");
      out.write("\t\t\t\t\t<li class=\"topline\"><a href='a_category.jsp' target='incFrame'>類別管理</a></li>\n");
      out.write("\t\t\t\t\t<li><a href='a_recommend.jsp' target='incFrame' >推薦管理</a></li>\n");
      out.write("\t\t\t\t</ul>\n");
      out.write("\t\t\t</li>\n");
      out.write("\t\t\t<li><a href='a_book.jsp' target='incFrame' >桌遊管理</a></li>\n");
      out.write("\t\t</ul>\n");
      out.write("\t</li>\n");
      out.write("\t<li>\n");
      out.write("\t\t<a href='a_member.jsp' target='incFrame'  class=\"menulink\">會員資料查詢</a>\n");
      out.write("\t</li>\n");
      out.write("\t<li>\n");
      out.write("\t\t<a href='a_borrow_record.jsp' target='incFrame'  class=\"menulink\">預約訂單及付款處理</a>\n");
      out.write("\t</li>\n");
      out.write("</ul>\n");
      out.write("<div class=\"arrow\"><img src=\"/images/arrow.png\" width=\"33\" height=\"38\" border=\"0\"></div>\n");
      out.write("</div>\n");
      out.write("</nav>\n");
      out.write("<div id=\"container\" >\n");
      out.write("\t<iframe name=\"incFrame\" id=\"incFrame\" frameborder=0 width=\"100%\" height=\"100%\" src=\"banner.jpg\"></iframe>\n");
      out.write("</div>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("<script language='javascript'>\n");
      out.write("\tvar menu=new menu.dd(\"menu\");\n");
      out.write("\tmenu.init(\"menu\",\"menuhover\");\n");
      out.write("\t(function(){\n");
      out.write("\t\t\n");
      out.write("\t\t$('.arrow').click(function(){\n");
      out.write("\t\t\t\n");
      out.write("\t\t\t$('nav').toggleClass('close');\t\n");
      out.write("\t\t\t$('#container').toggleClass('close');\n");
      out.write("\t\t\tsetTimeout(function(){\n");
      out.write("\t\t\t\t$('.arrow').toggleClass('rotate');\n");
      out.write("\t\t\t\t$('nav').toggleClass('opacity');\n");
      out.write("\t\t\t},500);\n");
      out.write("\t\t});\n");
      out.write("\n");
      out.write("\t})();\n");
      out.write("</script>\n");
      out.write("<noscript>Your browser does not support Script!</noscript>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
