/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M4
 * Generated at: 2016-06-06 08:44:45 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.controller;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.ArrayList;
import java.util.Date;
import java.util.Calendar;
import java.util.List;
import java.util.Map;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import teachDB.DbBean;

public final class newslist_005fsave_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {


		public boolean checkReq(Object obj){
			boolean check = false ;
			if(obj != null && !((String)obj).equals("")){
				check = true;
			}
			return check;
		}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.util.List");
    _jspx_imports_classes.add("java.util.Calendar");
    _jspx_imports_classes.add("java.util.Date");
    _jspx_imports_classes.add("teachDB.DbBean");
    _jspx_imports_classes.add("java.util.Map");
    _jspx_imports_classes.add("java.text.SimpleDateFormat");
    _jspx_imports_classes.add("java.text.ParseException");
    _jspx_imports_classes.add("java.util.ArrayList");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write('\n');

	request.setCharacterEncoding("UTF-8");
	int n_id = 0,n_order = 0,check_data = 0,result = 0;
	String n_date ="",n_title = "",n_content = "",updateSql = "",msg = "",status="";
	List updateList = null;
	Date updateNow = new Date(),publishDate = null;
	SimpleDateFormat sdf = new SimpleDateFormat("yyyy/MM/dd");
	Calendar Cal= Calendar.getInstance();   
	Cal.setTime(updateNow);   
	Cal.add(Calendar.HOUR_OF_DAY,8);   
	Date realtime = Cal.getTime();
	DbBean db = new DbBean();
	if(checkReq(request.getParameter("n_date")) && checkReq(request.getParameter("n_title"))  
		&& checkReq(request.getParameter("n_content")) ){
			n_date = (String)request.getParameter("n_date");
			n_title = (String)request.getParameter("n_title");
			n_content = (String)request.getParameter("n_content");
			try {
				publishDate = sdf.parse(n_date);
			} catch (ParseException e) {
				// TODO Auto-generated catch block
				e.printStackTrace();
			}
				if(checkReq(request.getParameter("n_id")) ){
					n_id = Integer.parseInt((String)request.getParameter("n_id"));
					List checkList = new ArrayList();
					checkList.add(n_title);
					checkList.add(n_id);
		         	List repeatList = db.SelectRSwhere("select * from newslist where deleteflag = 0 and n_title = ? and n_id != ?  ",checkList);
					if(repeatList.size() > 0){
						result = 2;
					}else{
						check_data = 2;
					}
				}else{
					List checkList = new ArrayList();
					checkList.add(n_title);
		         	List repeatList = db.SelectRSwhere("select * from newslist where deleteflag = 0 and n_title = ?  ",checkList);
					if(repeatList.size() > 0){
						result = 2;
					}else{
						check_data = 1;
						List orderList = db.SelectRS("select max(n_order) as maxorder from newslist where deleteflag = 0  ");
				     	if(orderList.size()>0){
				    		 for(int i=0;i<orderList.size();i++){
								Map map = (Map) orderList.get(i);
								if(map.get("maxorder") != null){
									n_order = (Integer)map.get("maxorder");
								}
							}
				     	}
					 	List deleteList = db.SelectRS("select min(n_id) as minidx from newslist where deleteflag = 1  ");
				     	if(deleteList.size()>0){
				    		 for(int i=0;i<deleteList.size();i++){
								Map map = (Map) deleteList.get(i);
								if(map.get("minidx") != null){
									check_data = 3;
									n_id = (Integer)map.get("minidx");
								}
							}
				     	}
					}
				}
					
	}
	switch(check_data) { 
    case 3: 
    	 updateList = new ArrayList();
		 updateList.add(n_title);
		 updateList.add(n_content);
		 updateList.add(publishDate);
		 updateList.add(n_order + 1 );
		 updateList.add(realtime);
		 updateList.add(realtime);
		 updateList.add(n_id);
		  updateSql   = "update newslist set n_title = ? ,n_content = ? , n_date = ? ,n_order = ? ";
		  updateSql  += " ,createtime = ?,updatetime = ? ,deleteflag = 0 where  n_id = ? ";
		  result = db.InsertData(updateSql, updateList); 
		  status = "新增";
        break; 
    case 2: 
    	 updateList = new ArrayList();
		 updateList.add(n_title);
		 updateList.add(n_content);
		 updateList.add(publishDate);
		 updateList.add(realtime);
		 updateList.add(n_id);
		  updateSql   = "update newslist set n_title = ? ,n_content = ? , n_date = ?  ";
		  updateSql  += "  ,updatetime = ? where  n_id = ? ";
		  result = db.InsertData(updateSql, updateList);
		  status = "修改";
        break; 
    case 1: 
    	updateList = new ArrayList();
		 updateList.add(n_title);
		 updateList.add(n_content);
		 updateList.add(publishDate);
		 updateList.add(n_order + 1);
		 updateList.add(realtime);
		 updateList.add(realtime);
		  updateSql   = " insert into newslist (n_title,n_content,n_date,n_order,createtime,updatetime,deleteflag) ";
		  updateSql  += " values(?,?,?,?,?,?,0) ";
		  result = db.InsertData(updateSql, updateList);
		  status = "新增";
        break;          
	}
	switch(result) { 
    case 2: 
    	msg = "消息標題:『" + n_title  +"』已存在，請重新輸入" ;
        break; 
    case 1: 
    	msg = "消息標題:『" + n_title +"』" +status +"成功" ;
        break; 
    default: 
    	msg = "消息標題:『" + n_title +"』" +status +"失敗" ; 
	}
		
	out.print("{\"success\":"+result);
	out.print(",\"msg\":\""+msg+"\"");
	out.print("}");

    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
